// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxT8MsiNVQgCnD7Jn9aFt-NDlOKlaq_VY',
    appId: '1:599856970241:web:0ca87c3680423ddd265e00',
    messagingSenderId: '599856970241',
    projectId: 'cavaa-e0406',
    authDomain: 'cavaa-e0406.firebaseapp.com',
    storageBucket: 'cavaa-e0406.firebasestorage.app',
    measurementId: 'G-XSCVKXR1G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG79gH1lTDHmji_fNdSTM0a0gO2ZMVdfw',
    appId: '1:599856970241:android:5a6ca9d2249e0e8f265e00',
    messagingSenderId: '599856970241',
    projectId: 'cavaa-e0406',
    storageBucket: 'cavaa-e0406.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh0pak_aBcm5RgpUwJk3YzIXH3Zs2nOuo',
    appId: '1:599856970241:ios:660b8633f2331bad265e00',
    messagingSenderId: '599856970241',
    projectId: 'cavaa-e0406',
    storageBucket: 'cavaa-e0406.firebasestorage.app',
    iosBundleId: 'com.example.cavaaCashier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh0pak_aBcm5RgpUwJk3YzIXH3Zs2nOuo',
    appId: '1:599856970241:ios:660b8633f2331bad265e00',
    messagingSenderId: '599856970241',
    projectId: 'cavaa-e0406',
    storageBucket: 'cavaa-e0406.firebasestorage.app',
    iosBundleId: 'com.example.cavaaCashier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxT8MsiNVQgCnD7Jn9aFt-NDlOKlaq_VY',
    appId: '1:599856970241:web:38b6f85704dd82c2265e00',
    messagingSenderId: '599856970241',
    projectId: 'cavaa-e0406',
    authDomain: 'cavaa-e0406.firebaseapp.com',
    storageBucket: 'cavaa-e0406.firebasestorage.app',
    measurementId: 'G-PCRJVHYZX6',
  );
}
